### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by mitsuhiko-y** [mitsuhiko-y/chat-space#8]
# IPアドレス
3.113.105.138

**Comment by miyu-yamamoto** [comment]
○○さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ サイドバーのグループ名と最新のメッセージの位置がずれている**
**○ サイドバーにあるアイコンの間に余分なスペースがある**
<img width="305" alt="スクリーンショット 2020-04-06 10 03 59" src="https://user-images.githubusercontent.com/59544869/78514843-74940180-77ee-11ea-8a9c-969f2dee4de4.png">

`↓こちらが見本です`
<img width="281" alt="スクリーンショット 2020-04-06 10 08 00" src="https://user-images.githubusercontent.com/59544869/78514865-93929380-77ee-11ea-900e-1cb0d7ecf3bc.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by mitsuhiko-y** [comment]
ご確認ありがとうございました！
